# Generated by Django 5.0.4 on 2024-04-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CALLBACK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Mobile_Number', models.CharField(max_length=10)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Class', models.CharField(max_length=20)),
                ('Goal', models.CharField(max_length=50)),
                ('Preferred_Mode', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Tearm_condition', models.BooleanField()),
                ('Permission', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
